package bestseller.javaprogramming.module2;

/*
 * Write a method that creates and initialises a two-dimensional array of double. The size of the array is determined by the arguments of 
 * the method, and the initialisation values are a range determined by beginning and ending values that are also arguments of the method. 
 * Create a second method that will print the array generated by the first method. In main( ) test the methods by creating and printing 
 * several different sizes of arrays.
 */
public class Excercise17 {
  
  public Excercise17() {
  }
  
  public static void main(String[] args) throws Exception{
    try{
      Excercise17 exObj = new Excercise17();
      double[][] arr = exObj.create2DArray(3,4,1);
      exObj.print2DArray(3,4,arr);
    }catch (Exception e){
      System.out.println(e);  
    }
  }
  
  private double[][] create2DArray(int rowCount, int colCount, int initStartVal){
    double[][] arr = new double[rowCount][colCount];  
    for(int i=0;i<rowCount;i++){
      for(int j=0;j<colCount;j++){
        arr[i][j] = initStartVal;
        initStartVal++;
      }
    }
    return arr;
  }
  
  private void print2DArray(int rowCount, int colCount, double[][] arr){
    
    for(int i=0;i<rowCount;i++){
      for(int j=0;j<colCount;j++){
        System.out.print(arr[i][j]  + "   ");
      }
      System.out.println("");
    }
  }
  
}
